// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#ifndef _TRH_2_8_INCH_UI_H
#define _TRH_2_8_INCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_screen_1.h"
#include "ui_screen_2.h"
#include "ui_screen_3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_info_icon_png);    // assets/Info_icon.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_1794831165);    // assets/home (2).png
LV_IMG_DECLARE(ui_img_disconnect_png);    // assets/Disconnect.png
// LV_IMG_DECLARE(ui_img_1686735119);
// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
