// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TRH_2_8_inch

#include "ui.h"

void ui_comp_Button2_create_hook(lv_obj_t * comp)
{
}
