// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#include "ui.h"

void WIFI_Disconnect(lv_event_t * e)
{
	// Your code here
}
