// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#include "ui.h"

lv_obj_t * ui_screen_3 = NULL;
lv_obj_t * ui_label35 = NULL;
lv_obj_t * ui_label22 = NULL;
lv_obj_t * ui_label23 = NULL;
lv_obj_t * ui_label25 = NULL;
lv_obj_t * ui_image4 = NULL;
// event funtions

// build funtions

void ui_screen_3_screen_init(void)
{
    ui_screen_3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_3, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen_3, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen_3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_screen_3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_screen_3, lv_color_hex(0xFAF6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_screen_3, LV_BLEND_MODE_NORMAL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_label35 = lv_label_create(ui_screen_3);
    lv_obj_set_width(ui_label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label35, 397);
    lv_obj_set_y(ui_label35, 19);
    lv_obj_set_align(ui_label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label35, "Loading......");
    lv_obj_set_style_text_color(ui_label35, lv_color_hex(0xFBF4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label35, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label22 = lv_label_create(ui_screen_3);
    lv_obj_set_width(ui_label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label22, 7);
    lv_obj_set_y(ui_label22, -16);
    lv_obj_set_align(ui_label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label22, "WIFI Disconnected");
    lv_obj_set_style_text_color(ui_label22, lv_color_hex(0xFAF6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label23 = lv_label_create(ui_screen_3);
    lv_obj_set_width(ui_label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label23, 7);
    lv_obj_set_y(ui_label23, 35);
    lv_obj_set_align(ui_label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label23, "");
    lv_obj_set_style_text_color(ui_label23, lv_color_hex(0x121010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label25 = lv_label_create(ui_screen_3);
    lv_obj_set_width(ui_label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label25, 7);
    lv_obj_set_y(ui_label25, 22);
    lv_obj_set_align(ui_label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label25, "Kindly Reconfigure");
    lv_obj_set_style_text_color(ui_label25, lv_color_hex(0xE30D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label25, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image4 = lv_image_create(ui_screen_3);
    lv_image_set_src(ui_image4, &ui_img_disconnect_png);
    lv_obj_set_width(ui_image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_image4, 3);
    lv_obj_set_y(ui_image4, -61);
    lv_obj_set_align(ui_image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_screen_3_screen_destroy(void)
{
    if(ui_screen_3) lv_obj_del(ui_screen_3);

    // NULL screen variables
    ui_screen_3 = NULL;
    ui_label35 = NULL;
    ui_label22 = NULL;
    ui_label23 = NULL;
    ui_label25 = NULL;
    ui_image4 = NULL;

}
