// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#ifndef UI_SCREEN_3_H
#define UI_SCREEN_3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_3
extern void ui_screen_3_screen_init(void);
extern void ui_screen_3_screen_destroy(void);
extern lv_obj_t * ui_screen_3;
extern lv_obj_t * ui_label35;
extern lv_obj_t * ui_label22;
extern lv_obj_t * ui_label23;
extern lv_obj_t * ui_label25;
extern lv_obj_t * ui_image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

