// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#ifndef UI_SCREEN_1_H
#define UI_SCREEN_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_1
extern void ui_screen_1_screen_init(void);
extern void ui_screen_1_screen_destroy(void);
extern lv_obj_t * ui_screen_1;
extern lv_obj_t * ui_panel6;
extern void ui_event_imgbutton1(lv_event_t * e);
extern lv_obj_t * ui_imgbutton1;
extern lv_obj_t * ui_label3;
extern lv_obj_t * ui_panel5;
extern lv_obj_t * ui_label15;
extern lv_obj_t * ui_label14;
extern lv_obj_t * ui_label5;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_label11;
extern lv_obj_t * ui_label30;
extern lv_obj_t * ui_spinner1;
extern lv_obj_t * ui_label9;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_screen_1_image1;
extern lv_obj_t * ui_screen_1_panel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

