// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#include "ui.h"

lv_obj_t * ui_screen_2 = NULL;
lv_obj_t * ui_panel1 = NULL;
lv_obj_t * ui_label6 = NULL;
lv_obj_t * ui_label7 = NULL;
lv_obj_t * ui_panel3 = NULL;
lv_obj_t * ui_imgbutton2 = NULL;
lv_obj_t * ui_imgbutton3 = NULL;
lv_obj_t * ui_label24 = NULL;
lv_obj_t * ui_label18 = NULL;
lv_obj_t * ui_label21 = NULL;
lv_obj_t * ui_label16 = NULL;
lv_obj_t * ui_label27 = NULL;
lv_obj_t * ui_label29 = NULL;
lv_obj_t * ui_label12 = NULL;
lv_obj_t * ui_label13 = NULL;
lv_obj_t * ui_label4 = NULL;
lv_obj_t * ui_label8 = NULL;
lv_obj_t * ui_label26 = NULL;
lv_obj_t * ui_label28 = NULL;
// event funtions
void ui_event_imgbutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen_1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_screen_1_screen_init);
        // _ui_screen_delete(&ui_screen_2_screen_destroy);
    }
}

void ui_event_imgbutton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_screen_3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_3_screen_init);
        // _ui_screen_delete(&ui_screen_2_screen_destroy);
    }
    if(event_code == LV_EVENT_RELEASED) {
        WIFI_Disconnect(e);
    }
}

// build funtions

void ui_screen_2_screen_init(void)
{
    ui_screen_2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_2, lv_color_hex(0x070610), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen_2, lv_color_hex(0x313041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen_2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_screen_2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_screen_2, lv_color_hex(0xFAF6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_screen_2, LV_BLEND_MODE_NORMAL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_panel1 = lv_obj_create(ui_screen_2);
    lv_obj_set_width(ui_panel1, 320);
    lv_obj_set_height(ui_panel1, 240);
    lv_obj_set_x(ui_panel1, 0);
    lv_obj_set_y(ui_panel1, -2);
    lv_obj_set_align(ui_panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel1, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panel1, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel1, lv_color_hex(0x313039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panel1, lv_color_hex(0x292839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_panel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label6 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label6, 7);
    lv_obj_set_y(ui_label6, -24);
    lv_obj_set_align(ui_label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label6, "");
    lv_obj_set_style_text_color(ui_label6, lv_color_hex(0xF8F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label7 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label7, 16);
    lv_obj_set_y(ui_label7, -61);
    lv_obj_set_align(ui_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label7, "");
    lv_obj_set_style_text_color(ui_label7, lv_color_hex(0xF8F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel3 = lv_obj_create(ui_panel1);
    lv_obj_set_width(ui_panel3, 320);
    lv_obj_set_height(ui_panel3, 40);
    lv_obj_set_x(ui_panel3, -1);
    lv_obj_set_y(ui_panel3, 95);
    lv_obj_set_align(ui_panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel3, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panel3, lv_color_hex(0x3DA0CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel3, lv_color_hex(0x313039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panel3, lv_color_hex(0x292839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgbutton2 = lv_imagebutton_create(ui_panel3);
    lv_imagebutton_set_src(ui_imgbutton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1794831165, NULL);
    lv_imagebutton_set_src(ui_imgbutton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1794831165, NULL);
    lv_obj_set_height(ui_imgbutton2, 32);
    lv_obj_set_width(ui_imgbutton2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_x(ui_imgbutton2, -130);
    lv_obj_set_y(ui_imgbutton2, 0);
    lv_obj_set_align(ui_imgbutton2, LV_ALIGN_CENTER);

    ui_imgbutton3 = lv_imagebutton_create(ui_panel3);
    lv_imagebutton_set_src(ui_imgbutton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_disconnect_png, NULL);
    lv_imagebutton_set_src(ui_imgbutton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1794831165, NULL);
    lv_obj_set_height(ui_imgbutton3, 32);
    lv_obj_set_width(ui_imgbutton3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_x(ui_imgbutton3, 130);
    lv_obj_set_y(ui_imgbutton3, 0);
    lv_obj_set_align(ui_imgbutton3, LV_ALIGN_CENTER);

    ui_label24 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label24, 147);
    lv_obj_set_y(ui_label24, -31);
    lv_obj_set_align(ui_label24, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label24, "------");
    lv_obj_set_style_text_color(ui_label24, lv_color_hex(0xF1F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label24, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label18 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label18, 147);
    lv_obj_set_y(ui_label18, -54);
    lv_obj_set_align(ui_label18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label18, "------");
    lv_obj_set_style_text_color(ui_label18, lv_color_hex(0xF0F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label18, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label21 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label21, 147);
    lv_obj_set_y(ui_label21, -83);
    lv_obj_set_align(ui_label21, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label21, "------");
    lv_obj_set_style_text_color(ui_label21, lv_color_hex(0xF8FBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label21, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label16 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label16, 146);
    lv_obj_set_y(ui_label16, -4);
    lv_obj_set_align(ui_label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label16, "------");
    lv_obj_set_style_text_color(ui_label16, lv_color_hex(0xF1F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label27 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label27, 146);
    lv_obj_set_y(ui_label27, 47);
    lv_obj_set_align(ui_label27, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label27, "------");
    lv_obj_set_style_text_color(ui_label27, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label27, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label29 = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label29, 146);
    lv_obj_set_y(ui_label29, 21);
    lv_obj_set_align(ui_label29, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label29, "------");
    lv_obj_set_style_text_color(ui_label29, lv_color_hex(0xFEFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label29, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label12 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label12, -24);
    lv_obj_set_y(ui_label12, -83);
    lv_obj_set_align(ui_label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label12, "IP :");
    lv_obj_set_style_text_color(ui_label12, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label13 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label13, -28);
    lv_obj_set_y(ui_label13, -58);
    lv_obj_set_align(ui_label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label13, "AP :");
    lv_obj_set_style_text_color(ui_label13, lv_color_hex(0xF7F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label4 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label4, -56);
    lv_obj_set_y(ui_label4, -34);
    lv_obj_set_align(ui_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label4, "Device ID :");
    lv_obj_set_style_text_color(ui_label4, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label8 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label8, -56);
    lv_obj_set_y(ui_label8, -6);
    lv_obj_set_align(ui_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label8, "Firmware :");
    lv_obj_set_style_text_color(ui_label8, lv_color_hex(0xFCF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label26 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label26, -72);
    lv_obj_set_y(ui_label26, 46);
    lv_obj_set_align(ui_label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label26, "Device Name :");
    lv_obj_set_style_text_color(ui_label26, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label26, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label26, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label28 = lv_label_create(ui_screen_2);
    lv_obj_set_width(ui_label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label28, -72);
    lv_obj_set_y(ui_label28, 20);
    lv_obj_set_align(ui_label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label28, "MAC Address :");
    lv_obj_set_style_text_color(ui_label28, lv_color_hex(0xFAF4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label28, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label28, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_imgbutton2, ui_event_imgbutton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgbutton3, ui_event_imgbutton3, LV_EVENT_ALL, NULL);

}

void ui_screen_2_screen_destroy(void)
{
    if(ui_screen_2) lv_obj_del(ui_screen_2);

    // NULL screen variables
    ui_screen_2 = NULL;
    ui_panel1 = NULL;
    ui_label6 = NULL;
    ui_label7 = NULL;
    ui_panel3 = NULL;
    ui_imgbutton2 = NULL;
    ui_imgbutton3 = NULL;
    ui_label24 = NULL;
    ui_label18 = NULL;
    ui_label21 = NULL;
    ui_label16 = NULL;
    ui_label27 = NULL;
    ui_label29 = NULL;
    ui_label12 = NULL;
    ui_label13 = NULL;
    ui_label4 = NULL;
    ui_label8 = NULL;
    ui_label26 = NULL;
    ui_label28 = NULL;

}
