// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#include "ui.h"
#include "esp_log.h"

lv_obj_t * ui_screen_1 = NULL;
lv_obj_t * ui_panel6 = NULL;
lv_obj_t * ui_imgbutton1 = NULL;
lv_obj_t * ui_label3 = NULL;
lv_obj_t * ui_panel5 = NULL;
lv_obj_t * ui_label15 = NULL;
lv_obj_t * ui_label14 = NULL;
lv_obj_t * ui_label5 = NULL;
lv_obj_t * ui_label1 = NULL;
lv_obj_t * ui_label11 = NULL;
lv_obj_t * ui_label30 = NULL;
lv_obj_t * ui_spinner1 = NULL;
lv_obj_t * ui_label9 = NULL;
lv_obj_t * ui_label2 = NULL;
lv_obj_t * ui_screen_1_image1 = NULL;
lv_obj_t * ui_screen_1_panel2 = NULL;
static lv_obj_t *ui_screen_color = NULL;

/* ================= BACK BUTTON CALLBACK ================= */
static void back_btn_event_cb(lv_event_t * e)
{
    lv_scr_load(ui_screen_2);
}

/* ================= IMAGE BUTTON EVENT ================= */
static void imgbutton_event_cb(lv_event_t * e)
{
    // ESP_LOGI(TAG,"imgbutton_event_cb invoked");
    if(lv_event_get_code(e) == LV_EVENT_PRESSED)
    {
        /* Create color screen only once */
        if(ui_screen_color == NULL)
        {
            ui_screen_color = lv_obj_create(NULL);
            lv_obj_remove_flag(ui_screen_color, LV_OBJ_FLAG_SCROLLABLE);

            /* Set background color (Blue example) */
            lv_obj_set_style_bg_color(ui_screen_color,
                                      lv_color_hex(0x0000FF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(ui_screen_color,
                                    LV_OPA_COVER,
                                    LV_PART_MAIN | LV_STATE_DEFAULT);

            /* Add back button */
            lv_obj_t * back_btn = lv_button_create(ui_screen_color);
            lv_obj_center(back_btn);

            lv_obj_t * label = lv_label_create(back_btn);
            lv_label_set_text(label, "Back");
            lv_obj_center(label);

            lv_obj_add_event_cb(back_btn,
                                back_btn_event_cb,
                                LV_EVENT_CLICKED,
                                NULL);
        }

        /* Switch screen */
        lv_scr_load(ui_screen_color);
    }
}

// event funtions
void ui_event_imgbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // ESP_LOGI(TAG, "event_code: %d", event_code);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen_2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_screen_2_screen_init);
        // _ui_screen_delete(&ui_screen_1_screen_destroy);
    }
}

// build funtions

void ui_screen_1_screen_init(void)
{
    ui_screen_1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_1, lv_color_hex(0x070610), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen_1, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen_1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_screen_1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_screen_1, LV_BLEND_MODE_NORMAL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_panel6 = lv_obj_create(ui_screen_1);
    lv_obj_set_width(ui_panel6, 320);
    lv_obj_set_height(ui_panel6, 240);
    // lv_obj_set_x(ui_panel6, -1);
    // lv_obj_set_y(ui_panel6, 7);
    lv_obj_set_align(ui_panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel6, lv_color_hex(0x0D0D0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panel6, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panel6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_panel6, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel6, lv_color_hex(0x313039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panel6, lv_color_hex(0x292839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgbutton1 = lv_imagebutton_create(ui_panel6);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_info_icon_png, NULL);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1794831165, NULL);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_1794831165, NULL);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1794831165, NULL);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1794831165, NULL);
    lv_imagebutton_set_src(ui_imgbutton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_1794831165, NULL);
    lv_obj_set_height(ui_imgbutton1, 34);
    lv_obj_set_width(ui_imgbutton1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_x(ui_imgbutton1, 139);
    lv_obj_set_y(ui_imgbutton1, -97);
    lv_obj_set_align(ui_imgbutton1, LV_ALIGN_CENTER);

    ui_label3 = lv_label_create(ui_panel6);
    lv_obj_set_width(ui_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label3, -71);
    lv_obj_set_y(ui_label3, -4);
    lv_obj_set_align(ui_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label3, "--.--");
    lv_obj_set_style_text_color(ui_label3, lv_color_hex(0xF4612E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel5 = lv_obj_create(ui_panel6);
    lv_obj_set_width(ui_panel5, 320);
    lv_obj_set_height(ui_panel5, 114);
    lv_obj_set_x(ui_panel5, 1);
    lv_obj_set_y(ui_panel5, 90);
    lv_obj_set_align(ui_panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel5, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panel5, lv_color_hex(0x3024B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel5, lv_color_hex(0x121213), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panel5, lv_color_hex(0x0B0B0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_recolor(ui_panel5, lv_color_hex(0x4040FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_panel5, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_label15 = lv_label_create(ui_panel5);
    lv_obj_set_width(ui_label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label15, -80);
    lv_obj_set_y(ui_label15, 4);
    lv_obj_set_align(ui_label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label15, "IP :");
    lv_obj_set_style_text_color(ui_label15, lv_color_hex(0xE7FA04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label14 = lv_label_create(ui_panel5);
    lv_obj_set_width(ui_label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label14, 83);
    lv_obj_set_y(ui_label14, 3);
    lv_obj_set_align(ui_label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label14, "AP :");
    lv_obj_set_style_text_color(ui_label14, lv_color_hex(0xD0FA05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label14, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label5 = lv_label_create(ui_panel6);
    lv_obj_set_width(ui_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label5, 86);
    lv_obj_set_y(ui_label5, -3);
    lv_obj_set_align(ui_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5, "--.--");
    lv_obj_set_style_text_color(ui_label5, lv_color_hex(0x01EFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_screen_1);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, -76);
    lv_obj_set_y(ui_label1, -49);
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "Temperature(°C)");
    lv_obj_set_style_text_color(ui_label1, lv_color_hex(0x0BF908), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label11 = lv_label_create(ui_screen_1);
    lv_obj_set_width(ui_label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label11, 818);
    lv_obj_set_y(ui_label11, 15);
    lv_obj_set_align(ui_label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label11, "Humidity");
    lv_obj_set_style_text_color(ui_label11, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label30 = lv_label_create(ui_screen_1);
    lv_obj_set_width(ui_label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label30, -81);
    lv_obj_set_y(ui_label30, 65);
    lv_obj_set_align(ui_label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label30, "MAC :");
    lv_obj_set_style_text_color(ui_label30, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label30, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spinner1 = lv_spinner_create(ui_screen_1);
    //lv_spinner_set_anim_params(ui_spinner1, 1000, 90);
    lv_obj_set_width(ui_spinner1, 27);
    lv_obj_set_height(ui_spinner1, 27);
    lv_obj_set_x(ui_spinner1, 6);
    lv_obj_set_y(ui_spinner1, 81);
    lv_obj_set_align(ui_spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_spinner1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_spinner1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_spinner1, lv_color_hex(0xF8FAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinner1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spinner1, lv_color_hex(0x0DFE48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinner1, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_label9 = lv_label_create(ui_screen_1);
    lv_obj_set_width(ui_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label9, 83);
    lv_obj_set_y(ui_label9, 64);
    lv_obj_set_align(ui_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label9, "CI-TC-XXXXXX");
    lv_obj_set_style_text_color(ui_label9, lv_color_hex(0xFCF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2 = lv_label_create(ui_screen_1);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label2, 84);
    lv_obj_set_y(ui_label2, -48);
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "Humidity(%)");
    lv_obj_set_style_text_color(ui_label2, lv_color_hex(0x0BF908), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_label2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_1_image1 = lv_image_create(ui_screen_1);
    lv_image_set_src(ui_screen_1_image1, &ui_img_logo_png);
    lv_obj_set_width(ui_screen_1_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screen_1_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_screen_1_image1, 5);
    lv_obj_set_y(ui_screen_1_image1, -94);
    lv_obj_set_align(ui_screen_1_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screen_1_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_screen_1_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screen_1_panel2 = lv_obj_create(ui_screen_1);
    lv_obj_set_width(ui_screen_1_panel2, 5);
    lv_obj_set_height(ui_screen_1_panel2, 50);
    lv_obj_set_x(ui_screen_1_panel2, 8);
    lv_obj_set_y(ui_screen_1_panel2, -8);
    lv_obj_set_align(ui_screen_1_panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_screen_1_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screen_1_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_screen_1_panel2, lv_color_hex(0xD0E51D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_1_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen_1_panel2, lv_color_hex(0xDBED2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_screen_1_panel2, lv_color_hex(0xF4FD38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_screen_1_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_screen_1_panel2, lv_color_hex(0xD5E53D), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_1_panel2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen_1_panel2, lv_color_hex(0xEEF03F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_screen_1_panel2, lv_color_hex(0xEAFF40), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_screen_1_panel2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_imgbutton1, ui_event_imgbutton1, LV_EVENT_ALL, NULL);

}

void ui_screen_1_screen_destroy(void)
{
    if(ui_screen_1) lv_obj_del(ui_screen_1);

    // NULL screen variables
    ui_screen_1 = NULL;
    ui_panel6 = NULL;
    ui_imgbutton1 = NULL;
    ui_label3 = NULL;
    ui_panel5 = NULL;
    ui_label15 = NULL;
    ui_label14 = NULL;
    ui_label5 = NULL;
    ui_label1 = NULL;
    ui_label11 = NULL;
    ui_label30 = NULL;
    ui_spinner1 = NULL;
    ui_label9 = NULL;
    ui_label2 = NULL;
    ui_screen_1_image1 = NULL;
    ui_screen_1_panel2 = NULL;

}
