// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: TRH_2_8_inch

#ifndef UI_SCREEN_2_H
#define UI_SCREEN_2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_2
extern void ui_screen_2_screen_init(void);
extern void ui_screen_2_screen_destroy(void);
extern lv_obj_t * ui_screen_2;
extern lv_obj_t * ui_panel1;
extern lv_obj_t * ui_label6;
extern lv_obj_t * ui_label7;
extern lv_obj_t * ui_panel3;
extern void ui_event_imgbutton2(lv_event_t * e);
extern lv_obj_t * ui_imgbutton2;
extern void ui_event_imgbutton3(lv_event_t * e);
extern lv_obj_t * ui_imgbutton3;
extern lv_obj_t * ui_label24;
extern lv_obj_t * ui_label18;
extern lv_obj_t * ui_label21;
extern lv_obj_t * ui_label16;
extern lv_obj_t * ui_label27;
extern lv_obj_t * ui_label29;
extern lv_obj_t * ui_label12;
extern lv_obj_t * ui_label13;
extern lv_obj_t * ui_label4;
extern lv_obj_t * ui_label8;
extern lv_obj_t * ui_label26;
extern lv_obj_t * ui_label28;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

